[tools]
python = "3.12"
uv = "latest"

[settings]
experimental = true
python.uv_venv_auto = true

[hooks]
postinstall = '''
  cd {{config_root}} &&
  git lfs install --local &&
  git lfs pull &&
  uv sync
'''

[tasks]
check = ["uv sync", "ruff check", "ruff format --check", "mypy", "pytest"]
otool = ["odrivetool --can can:can0 --no-usb"]
